### ISSUE TITLE
Create a sign up form to get more information about the recipes

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/tasteful-twist#12]

**Comment by tigerkaplan** [comment]
I have created a subscription form for users to receive email.

Now I am working on creating a registration/login/contact page.

**Comment by tigerkaplan** [comment]
Created a contact form to send messages to an admin with fetch API.

Created profile icon/button to sign up and sign in, also added social media sign up/ in.

The subscription button moved to the nav bar.

**Comment by tigerkaplan** [comment]
Admin receives email from users

sign up and sign in form was created but for some reason unable to receive a confirmation email. 

The subscription button was moved to the footer by Annie.
